### PR TITLE
Added Economy Context

### PR DESCRIPTION
**Pull request by northern-64bit**
Added Economy Context and many of GST:s economy commands. Here's the list of all new commands:

- !valuation sector (example: financial, country, ...)
- !currencies
- !glbonds
- !usbonds
- !futures
- !indicies
- !overview
- !feargreed (requires imgur api key and module pyimgur)

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Some feedback:
- feargreed isn't working properly for me because it loops forever searching for the exported image. May be related with ion. Also, I like what you did there, but wouldn't have an infinite loop. It's usually a bad practice to have an infinite loop, as you won't be able to tell that something is wrong and will "block" the bot. Instead we could do a timeout, that when it reached such, e.g. 10s or so we assumed an issue happened and output an error to the user.
- For valuation sector, I think we should do 2 things:
   - The first is to output the dataframe transpose, this should do: df.T. The idea is that the index is shown and demonstrates metrics such as PB, PE, Market Cap and so on. And each column is an industry/secotr.
   - The second is to only show 1 industry/sector at a time, to avoid this "big table". This pagination file looks promising https://github.com/SkullCrusher0003/paginator, to navigate through the sectors. Another idea would be to add as a reaction all the names of the columns, i.e. "sector", "industry",... and then the user pressed one and the dataframe shown would be of that one.

All the other commands worked well.

Let me know what you think!

**Review by DidierRLopes — APPROVED** [review]

**Comment by DidierRLopes** [comment]
I still can't use feargreed but am assuming the issue is on my end rather than on the code :)

**Comment by northern-64bit** [comment]
I'm trying to do feargreed similar to https://github.com/SkullCrusher0003/paginator, but I'll probably be done with it in 1-2 days. If you get any error message please share it with me, but the command works for me. I'll merge it then if it's ok. :P

**Comment by DidierRLopes** [comment]
> I'm trying to do feargreed similar to https://github.com/SkullCrusher0003/paginator, but I'll probably be done with it in 1-2 days. If you get any error message please share it with me, but the command works for me. I'll merge it then if it's ok. :P

Sounds great to me. 😋

**Pull request merged**
